version: '3.4'

services:
  web:
    image: penny-test
    build:
      context: .
      dockerfile: ./DockerFile
    environment:
      NODE_ENV: production
      # PORT: 3333
    ports:
      - 3333:3333
    # command: nx serve backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  # db:
  #     image: mongo:latest
  #     environment:
  #       - MONGODB_DATABASE="test"
  #     ports:
  #       - 27017:27017